### PR TITLE
Application Name Connection String

### PR DESCRIPTION
**Pull request by dehume**
Include `application_name` session variable when executing SQL with the Terraform provider. Making it a provider attribute with a default so it can be overwritten to something else in the Pulumi provider (otherwise this can just be hardcoded).

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
Is there a way to hide this from the docs? Would love to discourage people from overriding this.

**Comment by dehume** [comment]
> Is there a way to hide this from the docs? Would love to discourage people from overriding this.

I think we could edit the `index.md.tmpl` template and replace the `{{ .SchemaMarkdown | trimspace }}` reference with one we just hard code to only include the parameters we want to make public (so everything that isn't application name).

**Review by benesch — APPROVED** [review]
This is great, thank you!

**Review by morsapaes — APPROVED** [review]
Thank you for also considering the Pulumi provider, @dehume!

**Pull request merged**
