### PR TITLE
Prevent Privilege Read Errors

### PR DESCRIPTION
**Pull request by dehume**
Cleaning up the grant code which can lead to cryptic errors. Part of this was handling the privileges column from the system catalog as a string (now using `pq.StringArray`). Issues can come from attempting to generate the compound key that makes up grants and parsing out the compound key in order to correctly query the mz catalog.
```
panic: runtime error: index out of range [0] with length 0
```
If any issues arise with the parsing the key, the provider will set the key to `""` so the grant can be recreated rather than erroring.

Make the grant parsing functions more consistent and simple:
* `PrivilegeName`
* `ParseMzAclString`
* `MapGrantPrivileges`
* `MapDefaultGrantPrivileges`

### CODE REVIEW

**Comment by dehume** [comment]
Have to look into why the GHAs aren't picking up the package change

**Comment by dehume** [comment]
Any suggestion on the new `BrokerTransportFailure` failures. I didn't change anything around kafka connections

**Review by bobbyiliev — CHANGES_REQUESTED** [review]
As discussed internally, it sounds like that we might have to enable `security_protocol = "SASL_PLAINTEXT"` in the `connection.tf` to fix the failing tests

**Review by bobbyiliev — APPROVED** [review]
Looks good!

**Pull request merged**
